# Generated by Django 2.2.7 on 2019-11-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myHGapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myHGapp.Question'),
            preserve_default=False,
        ),
    ]
